# Generated by Django 5.0.7 on 2024-07-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_invoice_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=100, unique=True)),
                ('stored_quantities', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transfers', models.PositiveIntegerField()),
                ('expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('space', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage_capacity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
